{% set name = "rateslib" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rateslib-{{ version }}.tar.gz
  sha256: 7c7af2707f20974a70403689f84905757a4ed084e4c92229388d2fc30b331b04

build:
  script:
    # PyPy has weird sysconfigdata name
    # - rm -f $PREFIX/lib/pypy$PY_VER/_sysconfigdata.py  # [build_platform != target_platform and target_platform == "linux-ppc64le"]
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1,<2                         # [build_platform != target_platform]
    - { { compiler("c") } }
    - { { stdlib("c") } }
    - { { compiler("rust") } }
  host:
    - python >=3.9
    - maturin >=1.1
    - pip
  run:
    - python >=3.9
    - numpy >=1.21.5
    - matplotlib-base >=3.5.1
    - pandas >=1.4.1

test:
  imports:
    - rateslib
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A fixed income library for trading interest rates
  home: https://rateslib.readthedocs.io/en/stable/
  license: CC-BY-NC-ND-4.0
  license_family: CC
  license_file: LICENSE
  doc_url: https://rateslib.readthedocs.io/en/stable/
  dev_url: https://github.com/attack68/rateslib

extra:
  recipe-maintainers:
    - attack68
