{% set name = "rateslib" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rateslib-{{ version }}.tar.gz
  sha256: d831e1c3bd8b38f391f44dc4932e2cded942bf2792baef42504c12b03724a8a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >=3.9
    - numpy >=1.21.5
    - matplotlib-base >=3.5.1
    - pandas >=1.4.1

test:
  imports:
    - rateslib
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A fixed income library for trading interest rates
  home: https://rateslib.readthedocs.io/en/stable/
  license: CC-BY-NC-ND-4.0
  license_family: CC
  license_file: LICENSE
  doc_url: https://rateslib.readthedocs.io/en/stable/
  dev_url: https://github.com/attack68/rateslib

extra:
  recipe-maintainers:
    - attack68
