{% set name = "rateslib" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rateslib-{{ version }}.tar.gz
  sha256: 6778818c677a966dacb5d01a86e05e52bdb54d6e493e8bd460d9529e3b7b0b0e

build:
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1,<2                         # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("rust") }}
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python
    - numpy >=1.21.5,<3.0
    - matplotlib-base >=3.5.1,<4.0
    - pandas >=1.4.1,<3.0

test:
  imports:
    - rateslib
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A fixed income library for trading interest rates
  home: https://rateslib.com
  license: CC-BY-NC-ND-4.0
  license_family: CC
  license_file: LICENSE
  doc_url: https://rateslib.readthedocs.io/en/
  dev_url: https://github.com/attack68/rateslib

extra:
  recipe-maintainers:
    - attack68
    - NickAltmann
