{% set name = "rateslib" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rateslib-{{ version }}.tar.gz
  sha256: 1be827898e83ba5cad66d6fc088c41fb19e04dd98b4a58abbdb8bc78f228eb69

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >=3.9
    - numpy >=1.21.5
    - matplotlib-base >=3.5.1
    - pandas >=1.4.1

test:
  imports:
    - rateslib
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A fixed income library for trading interest rates
  home: https://rateslib.readthedocs.io/en/stable/
  license: CC-BY-NC-ND-4.0
  license_family: CC
  license_file: LICENSE
  doc_url: https://rateslib.readthedocs.io/en/stable/
  dev_url: https://github.com/attack68/rateslib

extra:
  recipe-maintainers:
    - attack68
